---
# Declare the resources that Concourse will continually check and use.
resources:
- name: git
  icon: gitlab
  type: git
  source:
    uri: https://github.com/ashok-mishraa/test-java-app.git
    branch: main
- name: git_manifest
  icon: gitlab
  type: git
  source:
    uri: https://github.com/ashok-mishraa/app-config-ArgoCD.git
    branch: main
- name: image
  type: registry-image
  icon: docker
  source:
    repository: ashokkumar54/java-application-concourse
    username: {{docker_user}}
    password: {{docker_pass}}
    tag: latest

jobs:

# This test job will fetch the source code from GitHub, and execute the test task.
- name: unit
  plan:
  - get: git
    version: latest # Just process the latest Git commit, not every commit (this is the default setting)
    trigger: true # Trigger this job whenever Concourse detects a new Resource version (i.e. a new Git commit)
  - task: run-unit-tests
    file: git/ci/concourse/tasks/unit-test.yml

# This build job will fetch the source code,
# then execute a 'build' task which is defined separately in the repository.
- name: package
  plan:
  - get: git_manifest
  - get: git # Concourse is stateless and needs to be given an external input to this Job.
    passed:
      - unit # The 'unit' job must have passed for this job to execute
    trigger: true
  - task: maven-package
    file: git/ci/concourse/tasks/maven-package.yml
  # Take the image built in the previous task, and push it to our Docker registry Resource
  - put: image
    params: {image: image/hello-java.tar}

- name: update_manifest
  serial: true
  plan:
  - get: git_manifest
    passed:
      - package
    trigger: true
  - task: manifest
    config:
      platform: linux
      image_resource:
        type: registry-image
        source:
          repository: ashokkumar54/python
          tag: 3-8-code
      inputs:
        - name: git_manifest
      run:
        path: /bin/sh
        args:
        - -c
        - |
          git checkout -b test-app-java-demo;python --version; pip install pyyaml;python git_manifest/update-manifest.py --e dev --n 1 --a test-java-app --t temp;git add -A; git commit -m "updating application manifest";git push --set-upstream origin test-app-java-demo;
