---
# A task to build a Docker image for a Java app with Jib

# Task definition

platform: linux
container_limits: {}

# Use the 'python:3.8-slim-buster' image from Docker Hub
image_resource:
  type: registry-image
  source:
    repository: ashokkumar54/python
    tag: 3-8-code

# We will provide an input called 'git' to this Task
# This causes Concourse to git checkout a specific commit.
# It also allows us to execute this step independently, for a specific Git commit.
# However, the parent pipeline only runs this task when the previous 'unit' job has passed.
inputs:
  - name: git_manifest

outputs:
  - name: image # Concourse creates this directory for us. This will hold the OCI image .tar

# What do we want this task to do?
# Tell Concourse the commands it should execute, in this Task
# Build an OCI image as a .tar file. Skip unit tests, because we've already run them in the previous Job
#     mvn compile jib:buildTar ... -DskipTests
# python update-manifest.py --e dev --n 1 --a test-java-app --t temp; git add -A; git commit -m "Updating the manifest file with version temp";git push --set-upstream origin test-java-app-temp;
run:
  path: /bin/sh
  args:
  - -c
  - |
    python update-manifest.py --e dev --n 1 --a test-java-app --t temp
